[build-system]
requires = ["scikit-build-core>=0.4.3", "cmake>=3.15", "ninja"]
build-backend = "scikit_build_core.build"

[project]
name = "bspot"
version = "0.0.1"
description = "Python bindings to BSP-OT"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
